basePath: /
definitions:
  dto.CreateNotificationRequest:
    properties:
      channel:
        allOf:
        - $ref: '#/definitions/models.Channel'
        enum:
        - email
        - telegram
        example: telegram
      message:
        example: test_message
        type: string
      recipient:
        description: адрес тг или email
        example: "796744183"
        type: string
      scheduled_at:
        example: "2025-11-01T10:40:00Z"
        type: string
    required:
    - channel
    - message
    - recipient
    - scheduled_at
    type: object
  dto.CreateNotificationResponse:
    properties:
      notification_id:
        type: integer
    type: object
  dto.GetNotificationResponse:
    properties:
      notification_status:
        $ref: '#/definitions/models.Status'
    type: object
  models.Channel:
    enum:
    - telegram
    - email
    type: string
    x-enum-varnames:
    - ChannelTelegram
    - ChannelEmail
  models.Status:
    enum:
    - scheduled
    - sent
    - cancelled
    - failed
    type: string
    x-enum-varnames:
    - StatusScheduled
    - StatusSent
    - StatusCancelled
    - StatusFailed
host: localhost:8081
info:
  contact: {}
  description: API for Delayed Notifier
  termsOfService: http://swagger.io/terms/
  title: Delayed Notifier
  version: "1.0"
paths:
  /notify:
    post:
      consumes:
      - application/json
      description: create notification with provided params
      parameters:
      - description: notification request
        in: body
        name: notification
        required: true
        schema:
          $ref: '#/definitions/dto.CreateNotificationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CreateNotificationResponse'
        "400":
          description: impossible to create notification
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: failed to create notification
          schema:
            additionalProperties:
              type: string
            type: object
      summary: create notification
      tags:
      - notify
  /notify/{notification_id}:
    delete:
      consumes:
      - application/json
      description: delete notification by notification_id
      parameters:
      - description: notification ID
        in: path
        name: notification_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: delete notification successful
          schema:
            type: string
        "400":
          description: invalid notification_id
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: failed to delete notification
          schema:
            additionalProperties:
              type: string
            type: object
      summary: delete notification
      tags:
      - notify
    get:
      consumes:
      - application/json
      description: get notification status by notification_id
      parameters:
      - description: notification ID
        in: path
        name: notification_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetNotificationResponse'
        "400":
          description: invalid notification_id
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: failed to get notification status
          schema:
            additionalProperties:
              type: string
            type: object
      summary: get notification status
      tags:
      - notify
swagger: "2.0"
